name: aws4dart
version: 0.1.0
author: Lars Tackmann <lars@solvr.io>
description: AWS SDK for Dart
homepage: https://github.com/ltackmann/aws4dart
dependencies:
  dice:
    git: git://github.com/ltackmann/dice.git
  http: any
  log4dart: any
  meta: any
  unittest: any
  xml: 
    git: git@github.com:prujohn/dart-xml.git

