name: aws4dart
version: 0.1.0
author: Lars Tackmann <lars@solvr.io>
description: A SDK for using Amazon web services from Dart
homepage: https://github.com/Solvr/aws4dart
dependencies:
  unittest: any
  xml: any
  log4dart: any
  dice:
    git: git://github.com/ltackmann/dice.git
